### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by GeorgeSalu** [kazuki43zoo/mybatis-micronaut#2]
it would be great to have a mybatis plugin for micronaut

**Comment by huyi0912** [comment]
Micronaut's guide on using Mybatis seems cumbersome. 
But trying using this bridge against latest Micronaut 4.1.5 seems lots have broked. 
Easy part like javax have changed to jarkarta.
But difficult one is that SqlSessionFactory.openSession will throws

`io.micronaut.data.connection.exceptions.NoConnectionException: No current connection present. Consider declaring @Connectable or @Transactional on the surrounding method
	at io.micronaut.data.connection.exceptions.NoConnectionException.notFoundInAdvice(NoConnectionException.java:49)
	at io.micronaut.data.connection.jdbc.advice.ContextualConnectionInterceptor.intercept(ContextualConnectionInterceptor.java:58)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.data.connection.jdbc.advice.ContextualConnection$Intercepted.getAutoCommit(Unknown Source)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.setDesiredAutoCommit(JdbcTransaction.java:105)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:149)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:67)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getConnection(DefaultSqlSession.java:297)`

Any idea? Really hope this project can be better maintained!
